---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/norwoodj/helm-docs.git
    rev: v1.13.1
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
  - repo: local
    hooks:
      - id: chart-lint
        name: Run Chart Lint Test
        language: system
        entry: 'ct lint --all --validate-maintainers=false --config .github/ct.yaml charts/'
#  - repo: local
#    hooks:
#      - id: go-test
#        name: Run Go Test
#        language: system
#        entry: 'go test -v -cover ./...'
#  - repo: local
#    hooks:
#      - id: golangci-lint
#        name: Run Golangci-lint
#        language: system
#        entry: "golangci-lint run --out-format=github-actions --timeout=3m --skip-dirs=charts --skip-files '\\*.[yaml|md]'"
  - repo: https://github.com/drewbernetes/pre-commits.git
    rev: v0.1.0
    hooks:
      - id: docker
        args:
          - --image-name
          - dogkat
          - --dockerfile-path
          - ./docker/Dockerfile
          - --context
          - .
  - repo: https://github.com/drewbernetes/pre-commits.git
    rev: v0.1.0
    hooks:
      - id: trivy
        args:
          - fs
          - .
  - repo: https://github.com/drewbernetes/pre-commits.git
    rev: v0.1.0
    hooks:
      - id: trivy
        args:
          - image
          - --severity
          - HIGH,CRITICAL
          - --ignorefile
          - .trivyignore
          - local/dogkat:0.0.0
