---

# Default values for HA e2e-testing basic.

core:
  enabled: false
  nginx:
    image:
      repo: cgr.dev/chainguard/nginx
      tag: latest  # 1.25.4
    exporterImage:
      repo: nginx/nginx-prometheus-exporter@sha256
      tag: 6477cf3bddc4e042d3496856fb2e8e382301bac47fb18cb83924389717261cb1
    serviceAccountName: "nginx"
    resources: {}
    # requests:
    #   memory: "500Mi"
    #   cpu: "500m"
    # limits:
    #   memory: "1Gi"
    #   cpu: "1000m"
  php:
    image:
      repo: drewviles/php-pdo@sha256
      tag: 4485f4a33423d3ca5cceb2600e72e32550ce98ce628c05dc175c7a5763faa616
  postgres:
    image:
      repo: postgres@sha256
      tag: d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf
    statefulSet:
      persistentData:
        enabled: true
        storageClassName: "longhorn"

gpu:
  enabled: false
  numberOfGPUs: 1
  image:
    # -- The repo to be used
    repo: nvcr.io/nvidia/k8s/cuda-sample@sha256
    # -- The tag to be used
    tag: ac53daee629763d712e1361b77e4c4f4ad146148f9dffc6288a75732270c6e85  # 12.5.0
  resources: {}
  nodeLabelSelectors:
    nvidia.com/gpu.present: "true"

ingress:
  enabled: false
  annotations: {}
  # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # external-dns.alpha.kubernetes.io/target: "example.uk"
  # external-dns.alpha.kubernetes.io/hostname: "example.uk"
  # external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  className: nginx
  host: test.example.uk
  tls:
    - hosts:
        - test.example.uk
      secretName: test-secret

monitoring:
  grafana:
    dashboards: false
  serviceMonitor:
    enabled: false
