---

# Default values for HA e2e-testing basic.

core:
  enabled: false
  nginx:
    image:
      repo: cgr.dev/chainguard/nginx
      tag: latest  # 1.25.4
    exporterImage:
      repo: nginx/nginx-prometheus-exporter@sha256
      tag: d710e0ff2505a7037dd21e47eae07025010c0de08a6247d1a704824823becfd0  # 1.1.0
    serviceAccountName: "nginx"
    resources: {}
    # requests:
    #   memory: "500Mi"
    #   cpu: "500m"
    # limits:
    #   memory: "1Gi"
    #   cpu: "1000m"
  php:
    image:
      repo: drewviles/php-pdo@sha256
      tag: 27bacb42ac9bd8dc4b1d49cac40763eba0fa18b9ebaa4f6792383fe5ec27eded  # v1.2.0
  postgres:
    image:
      repo: postgres@sha256
      tag: 49fd8c13fbd0eb92572df9884ca41882a036beac0f12e520274be85e7e7806e9  #  16.2-alpine
    statefulSet:
      persistentData:
        enabled: true
        storageClassName: "cinder"

gpu:
  enabled: false
  numberOfGPUs: 1
  image:
    # -- The repo to be used
    repo: nvcr.io/nvidia/k8s/cuda-sample@sha256
    # -- The tag to be used
    tag: 04a20bfaf69363ec3f15fc1cdb0abc0efabeb6fb6b3a1b9cf4a575ae7b1d81d1  # 11.7.1
  resources: {}
  nodeLabelSelectors:
    nvidia.com/gpu.present: "true"

ingress:
  enabled: false
  annotations: {}
  # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # external-dns.alpha.kubernetes.io/target: "example.uk"
  # external-dns.alpha.kubernetes.io/hostname: "example.uk"
  # external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  className: nginx
  host: test.example.uk
  tls:
    - hosts:
        - test.example.uk
      secretName: test-secret

monitoring:
  grafana:
    dashboards: false
  serviceMonitor:
    enabled: false
