{{- if .Values.gpu.enabled -}}
---

apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "e2e-testing.annotations" . | nindent 4 }}
    {{- include "e2e-testing.gpu.annotations" . | nindent 4 }}
  labels:
    {{- include "e2e-testing.labels" . | nindent 4 }}
    {{- include "e2e-testing.gpu.labels" . | nindent 4 }}
spec:
  restartPolicy: OnFailure
  nodeSelector:
    {{- toYaml .Values.gpu.nodeLabelSelectors| nindent 4 }}
  containers:
    - name: nvidia-vectoradd
      image: {{.Values.gpu.image.repo}}:{{.Values.gpu.image.tag}}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      {{- if .Values.gpu.resources }}
      resources:
        "nvidia.com/gpu": {{ .Values.gpu.numberOfGPUs }}
        {{- toYaml .Values.gpu.resources | nindent 12 }}
      {{- end }}
{{- end }}

