{{- if or .Values.core.enabled  .Values.ingress.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-e2e
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "e2e-testing.annotations" . | nindent 4 }}
    {{- include "e2e-testing.nginx.annotations" . | nindent 4 }}
  labels:
    {{- include "e2e-testing.labels" . | nindent 4 }}
    {{- include "e2e-testing.nginx.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
    - port: 9113
      protocol: TCP
      targetPort: 9113
      name: http-metrics
  selector:
    app: web-frontend
  type: ClusterIP
{{- end }}
