{{- if or .Values.core.enabled  .Values.ingress.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "e2e-testing.annotations" . | nindent 4 }}
    {{- include "e2e-testing.nginx.annotations" . | nindent 4 }}
  labels:
    {{- include "e2e-testing.labels" . | nindent 4 }}
    {{- include "e2e-testing.nginx.labels" . | nindent 4 }}
data:
  default: |
    log_format custom_format '$remote_addr - $remote_user [$time_local]'
      '"$request" $status $body_bytes_sent'
      '"$http_referer" "$http_user_agent"'
      '$upstream_response_time';

    server {
      listen       8080 default_server;
      listen  [::]:8080 default_server;
      server_name  _;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log custom_format;
      root /usr/share/nginx/html;
      index    index.html index.htm index.php;

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass localhost:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }

      location /stub_status {
          stub_status on;
      }
    }
{{- end }}
