---

apiVersion: v1
kind: Secret
metadata:
  name: pg-password
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "e2e-testing.annotations" . | nindent 4 }}
    {{- include "e2e-testing.psql.annotations" . | nindent 4 }}
  labels:
    {{- include "e2e-testing.labels" . | nindent 4 }}
    {{- include "e2e-testing.psql.labels" . | nindent 4 }}
data:
  passwd: ZTJlLXBhc3N3b3JkCg==
