---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "e2e-testing.annotations" . | nindent 4 }}
    {{- include "e2e-testing.psql.annotations" . | nindent 4 }}
  labels:
    {{- include "e2e-testing.labels" . | nindent 4 }}
    {{- include "e2e-testing.psql.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: database-backend
