---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-init
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "e2e-testing.annotations" . | nindent 4 }}
    {{- include "e2e-testing.psql.annotations" . | nindent 4 }}
  labels:
    {{- include "e2e-testing.labels" . | nindent 4 }}
    {{- include "e2e-testing.psql.labels" . | nindent 4 }}
data:
  "init-user-db.sh": |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOF
    	CREATE TABLE IF NOT EXISTS web (id SERIAL PRIMARY KEY, value VARCHAR(10) NOT NULL );
        INSERT INTO web (value) VALUES('ok');
    EOF
